[package]
name = "swc-plugin-minify-graphql-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
afl = "0.15"
arbitrary = "1.3"
graphql-minify = { version = "0.1.0", path = "../packages/graphql-minify" }

# let's use `cargo-run-bin` while there is no built-in solution for
# https://github.com/rust-lang/cargo/issues/2267
[workspace.metadata.bin]
cargo-binstall = { version = "1.10.7", locked = true }
cargo-afl = { version = "0.15.11", locked = true, bins = ["cargo-afl"] }

[workspace]
members = ["."]

[[bin]]
name = "minify"
path = "fuzz_targets/minify.rs"
test = false
doc = false
bench = false
