[package]
name = "graphql-minify"
version = "0.1.0"
authors = ["Daniel Lehr <daniel@launchport.io>"]
edition.workspace = true
keywords = ["graphql", "minify", "minification", "query", "schema"]
license = "MIT"
publish.workspace = true
repository = "https://github.com/dan-lee/graphql-minify-rs"
description = "Minify GraphQL queries"

[dependencies]
bumpalo = { version = "3.16.0", features = ["collections"] }
logos = "0.14.2"
memchr = "2.7.4"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["real_blackbox"] }
graphql_semantic_compare = { version = "*", path = "../graphql_semantic_compare" }
indoc = "2.0"
test_each_file = "0.3"

[[bench]]
name = "minify"
harness = false

[[example]]
name = "github_schema"
